export const LST_NFTS = [
  {
    id: 'nft1',
    iconUrl: '/blizzard-nft.png',
    token: '0xf25f...E5fa',
    symbol: 'Staked',
    totalStaked: '643,2',
    toWithdraw: 8723.231,
    status: 'Withdrawing',
  },
  {
    id: 'nft2',
    iconUrl: '/blizzard-nft.png',
    token: '0xf25f...E5fa',
    symbol: 'Staked',
    totalStaked: '643,2',
    toWithdraw: 8723.231,
    status: 'Ready to Get',
  },
  {
    id: 'nft3',
    iconUrl: '/blizzard-nft.png',
    token: '0xf25f...E5fa',
    symbol: 'Staked',
    totalStaked: '643,2',
    toWithdraw: 8723.231,
    status: '12:10',
  },
  {
    id: 'nft4',
    iconUrl: '/blizzard-nft.png',
    token: '0xf25f...E5fa',
    symbol: 'Staked',
    totalStaked: '643,2',
    toWithdraw: 8723.231,
    status: 'Read to Withdraw',
  },
  {
    id: 'nft5',
    iconUrl: '/blizzard-nft.png',
    token: '0xf25f...E5fa',
    symbol: 'Staked',
    totalStaked: '643,2',
    toWithdraw: 8723.231,
    status: 'Staked',
  },
];
