export const LST_NFTS = [
  {
    id: 'nft1',
    name: '0xf25f...E5fa',
    subtitle: 'Staked',
    iconBg: '#3366FF',
    totalStaked: '643,2',
    toWithdraw: '$253,28',
    status: 'Withdrawing',
    action: 'Withdraw',
  },
  {
    id: 'nft2',
    name: '0xf25f...E5fa',
    subtitle: 'Staked',
    iconBg: '#00BFFF',
    totalStaked: '643,2',
    toWithdraw: '$253,28',
    status: 'Ready to Get',
    action: 'Get LST',
  },
  {
    id: 'nft3',
    name: '0xf25f...E5fa',
    subtitle: 'Staked',
    iconBg: '#00BFFF',
    totalStaked: '643,2',
    toWithdraw: '$253,28',
    status: '1210',
    action: 'Get LST',
  },
  {
    id: 'nft4',
    name: '0xf25f...E5fa',
    subtitle: 'Staked',
    iconBg: '#3366FF',
    totalStaked: '643,2',
    toWithdraw: '$253,28',
    status: 'Ready To Withdraw',
    action: 'Withdraw',
  },
  {
    id: 'nft5',
    name: '0xf25f...E5fa',
    subtitle: 'Staked',
    iconBg: '#3366FF',
    totalStaked: '643,2',
    toWithdraw: '$253,28',
    status: 'Staked',
    action: 'Withdraw',
  },
];
